from gtts import gTTS
import os

def generate_audio(text, filename):
    tts = gTTS(text=text, lang='en')
    tts.save(f'../public/audio/{filename}')

# 生成音频文件
# 在 audio_files 字典中添加新的音频配置
audio_files = {
    # 元音字母发音
    'a_sound.mp3': 'æ',
    'e_sound.mp3': 'e',
    'i_sound.mp3': 'ɪ',
    'o_sound.mp3': 'ɒ',
    'u_sound.mp3': 'ʌ',
    'a_long_sound.mp3': 'eɪ',
    'e_long_sound.mp3': 'iː',
    'i_long_sound.mp3': 'aɪ',
    'o_long_sound.mp3': 'əʊ',
    'u_long_sound.mp3': 'juː',

    # 原有的音频文件配置保持不变
    'a.mp3': 'A',
    'e.mp3': 'E',
    'i.mp3': 'I',
    'o.mp3': 'O',
    'u.mp3': 'U',
    'cat.mp3': 'cat',
    'bed.mp3': 'bed',
    'bee.mp3': 'bee',
    'egg.mp3': 'egg',
    'pig.mp3': 'pig',
    'kite.mp3': 'kite',
    'ink.mp3': 'ink',
    'dog.mp3': 'dog',
    'nose.mp3': 'nose',
    'orange.mp3': 'orange',
    'cup.mp3': 'cup',
    'cube.mp3': 'cube',
    'umbrella.mp3': 'umbrella',
    
    # 额外的元音示例词
    'ape.mp3': 'ape',
    'ace.mp3': 'ace',
    'ate.mp3': 'ate',
    'eve.mp3': 'eve',
    'eat.mp3': 'eat',
    'each.mp3': 'each',
    'ice.mp3': 'ice',
    'item.mp3': 'item',
    'iron.mp3': 'iron',
    'oak.mp3': 'oak',
    'open.mp3': 'open',
    'over.mp3': 'over',
    'use.mp3': 'use',
    'unit.mp3': 'unit',
    'uniform.mp3': 'uniform',

    # 辅音字母
    'b.mp3': 'B',
    'c.mp3': 'C',
    'd.mp3': 'D',
    'f.mp3': 'F',
    'g.mp3': 'G',
    'h.mp3': 'H',
    'j.mp3': 'J',
    'k.mp3': 'K',
    'l.mp3': 'L',
    'm.mp3': 'M',
    'n.mp3': 'N',
    'p.mp3': 'P',
    'q.mp3': 'Q',
    'r.mp3': 'R',
    's.mp3': 'S',
    't.mp3': 'T',
    'v.mp3': 'V',
    'w.mp3': 'W',
    'x.mp3': 'X',
    'y.mp3': 'Y',
    'z.mp3': 'Z',

    # 辅音示例词
    'ball.mp3': 'ball',
    'bed.mp3': 'bed',
    'boy.mp3': 'boy',
    'book.mp3': 'book',
    'cat.mp3': 'cat',
    'cup.mp3': 'cup',
    'car.mp3': 'car',
    'cake.mp3': 'cake',
    'dog.mp3': 'dog',
    'duck.mp3': 'duck',
    'door.mp3': 'door',
    'desk.mp3': 'desk',
    'fish.mp3': 'fish',
    'fan.mp3': 'fan',
    'fox.mp3': 'fox',
    'food.mp3': 'food',
    'girl.mp3': 'girl',
    'game.mp3': 'game',
    'goat.mp3': 'goat',
    'gift.mp3': 'gift',
    'hat.mp3': 'hat',
    'hand.mp3': 'hand',
    'home.mp3': 'home',
    'horse.mp3': 'horse',
    'jam.mp3': 'jam',
    'jump.mp3': 'jump',
    'juice.mp3': 'juice',
    'jet.mp3': 'jet',
    'king.mp3': 'king',
    'kid.mp3': 'kid',
    'kite.mp3': 'kite',
    'key.mp3': 'key',
    'lion.mp3': 'lion',
    'leg.mp3': 'leg',
    'leaf.mp3': 'leaf',
    'lamp.mp3': 'lamp',
    'moon.mp3': 'moon',
    'map.mp3': 'map',
    'milk.mp3': 'milk',
    'mouse.mp3': 'mouse',
    'nest.mp3': 'nest',
    'net.mp3': 'net',
    'nose.mp3': 'nose',
    'nut.mp3': 'nut',
    'pig.mp3': 'pig',
    'pen.mp3': 'pen',
    'pan.mp3': 'pan',
    'pet.mp3': 'pet',
    'queen.mp3': 'queen',
    'quick.mp3': 'quick',
    'quiet.mp3': 'quiet',
    'quiz.mp3': 'quiz',
    'red.mp3': 'red',
    'run.mp3': 'run',
    'rain.mp3': 'rain',
    'rat.mp3': 'rat',
    'sun.mp3': 'sun',
    'sit.mp3': 'sit',
    'sea.mp3': 'sea',
    'sock.mp3': 'sock',
    'top.mp3': 'top',
    'ten.mp3': 'ten',
    'toy.mp3': 'toy',
    'tree.mp3': 'tree',
    'van.mp3': 'van',
    'vet.mp3': 'vet',
    'vest.mp3': 'vest',
    'vine.mp3': 'vine',
    'web.mp3': 'web',
    'win.mp3': 'win',
    'walk.mp3': 'walk',
    'wall.mp3': 'wall',
    'box.mp3': 'box',
    'six.mp3': 'six',
    'mix.mp3': 'mix',
    'yes.mp3': 'yes',
    'you.mp3': 'you',
    'yard.mp3': 'yard',
    'year.mp3': 'year',
    'zoo.mp3': 'zoo',
    'zip.mp3': 'zip',
    'zero.mp3': 'zero',
    'zebra.mp3': 'zebra',
    
    # 音素组合发音和示例词
    'bl.mp3': 'bl',
    'blue.mp3': 'blue',
    'black.mp3': 'black',
    'block.mp3': 'block',
    'blow.mp3': 'blow',
    
    'br.mp3': 'br',
    'bread.mp3': 'bread',
    'brown.mp3': 'brown',
    'brush.mp3': 'brush',
    'bridge.mp3': 'bridge',
    
    'cl.mp3': 'cl',
    'clock.mp3': 'clock',
    'cloud.mp3': 'cloud',
    'clean.mp3': 'clean',
    'climb.mp3': 'climb',
    
    'cr.mp3': 'cr',
    'crab.mp3': 'crab',
    'cry.mp3': 'cry',
    'crown.mp3': 'crown',
    'crane.mp3': 'crane',
    
    'dr.mp3': 'dr',
    'drum.mp3': 'drum',
    'draw.mp3': 'draw',
    'drink.mp3': 'drink',
    'dress.mp3': 'dress',
    
    'fl.mp3': 'fl',
    'flag.mp3': 'flag',
    'fly.mp3': 'fly',
    'flower.mp3': 'flower',
    'floor.mp3': 'floor',
    
    'fr.mp3': 'fr',
    'frog.mp3': 'frog',
    'friend.mp3': 'friend',
    'fruit.mp3': 'fruit',
    'freeze.mp3': 'freeze',
    
    'gl.mp3': 'gl',
    'glass.mp3': 'glass',
    'glue.mp3': 'glue',
    'globe.mp3': 'globe',
    'glove.mp3': 'glove',
    
    'gr.mp3': 'gr',
    'green.mp3': 'green',
    'grass.mp3': 'grass',
    'grape.mp3': 'grape',
    'grow.mp3': 'grow',
    
    'pl.mp3': 'pl',
    'play.mp3': 'play',
    'plane.mp3': 'plane',
    'plant.mp3': 'plant',
    'plus.mp3': 'plus',
    
    'pr.mp3': 'pr',
    'price.mp3': 'price',
    'proud.mp3': 'proud',
    'print.mp3': 'print',
    'pray.mp3': 'pray',
    
    'sc.mp3': 'sc',
    'scan.mp3': 'scan',
    'school.mp3': 'school',
    'score.mp3': 'score',
    'scarf.mp3': 'scarf',
    
    'sk.mp3': 'sk',
    'sky.mp3': 'sky',
    'skip.mp3': 'skip',
    'skin.mp3': 'skin',
    'skull.mp3': 'skull',
    
    'sl.mp3': 'sl',
    'sleep.mp3': 'sleep',
    'slide.mp3': 'slide',
    'slow.mp3': 'slow',
    'slice.mp3': 'slice',
    
    'sm.mp3': 'sm',
    'smile.mp3': 'smile',
    'small.mp3': 'small',
    'smart.mp3': 'smart',
    'smoke.mp3': 'smoke',
    
    'sn.mp3': 'sn',
    'snake.mp3': 'snake',
    'snow.mp3': 'snow',
    'snail.mp3': 'snail',
    'snap.mp3': 'snap',
    
    'sp.mp3': 'sp',
    'space.mp3': 'space',
    'speak.mp3': 'speak',
    'spoon.mp3': 'spoon',
    'sport.mp3': 'sport',
    
    'st.mp3': 'st',
    'star.mp3': 'star',
    'stop.mp3': 'stop',
    'stone.mp3': 'stone',
    'stick.mp3': 'stick',
    
    'sw.mp3': 'sw',
    'swim.mp3': 'swim',
    'sweet.mp3': 'sweet',
    'swing.mp3': 'swing',
    'sweep.mp3': 'sweep',
    
    'tr.mp3': 'tr',
    'tree.mp3': 'tree',
    'train.mp3': 'train',
    'truck.mp3': 'truck',
    'try.mp3': 'try',
}

# 确保音频目录存在
os.makedirs('../public/audio', exist_ok=True)

# 只生成不存在的音频文件
for filename, text in audio_files.items():
    file_path = f'../public/audio/{filename}'
    if not os.path.exists(file_path):
        print(f'生成音频: {filename}')
        generate_audio(text, filename)
    else:
        print(f'跳过已存在的音频: {filename}')