from gtts import gTTS
import os

def generate_audio(text, filename):
    tts = gTTS(text=text, lang='en')
    tts.save(f'../public/audio/{filename}')

# 生成音频文件
audio_files = {
    # 元音字母
    'a.mp3': 'A',
    'e.mp3': 'E',
    'i.mp3': 'I',
    'o.mp3': 'O',
    'u.mp3': 'U',

    # 元音示例词
    'cat.mp3': 'cat',
    'cake.mp3': 'cake',
    'apple.mp3': 'apple',
    'bed.mp3': 'bed',
    'bee.mp3': 'bee',
    'egg.mp3': 'egg',
    'pig.mp3': 'pig',
    'kite.mp3': 'kite',
    'ink.mp3': 'ink',
    'dog.mp3': 'dog',
    'nose.mp3': 'nose',
    'orange.mp3': 'orange',
    'cup.mp3': 'cup',
    'cube.mp3': 'cube',
    'umbrella.mp3': 'umbrella',
    
    # 额外的元音示例词
    'ape.mp3': 'ape',
    'ace.mp3': 'ace',
    'ate.mp3': 'ate',
    'eve.mp3': 'eve',
    'eat.mp3': 'eat',
    'each.mp3': 'each',
    'ice.mp3': 'ice',
    'item.mp3': 'item',
    'iron.mp3': 'iron',
    'oak.mp3': 'oak',
    'open.mp3': 'open',
    'over.mp3': 'over',
    'use.mp3': 'use',
    'unit.mp3': 'unit',
    'uniform.mp3': 'uniform',

    # 辅音字母
    'b.mp3': 'B',
    'c.mp3': 'C',
    'd.mp3': 'D',
    'f.mp3': 'F',
    'g.mp3': 'G',
    'h.mp3': 'H',
    'j.mp3': 'J',
    'k.mp3': 'K',
    'l.mp3': 'L',
    'm.mp3': 'M',
    'n.mp3': 'N',
    'p.mp3': 'P',
    'q.mp3': 'Q',
    'r.mp3': 'R',
    's.mp3': 'S',
    't.mp3': 'T',
    'v.mp3': 'V',
    'w.mp3': 'W',
    'x.mp3': 'X',
    'y.mp3': 'Y',
    'z.mp3': 'Z',

    # 辅音示例词
    'ball.mp3': 'ball',
    'bed.mp3': 'bed',
    'boy.mp3': 'boy',
    'book.mp3': 'book',
    'cat.mp3': 'cat',
    'cup.mp3': 'cup',
    'car.mp3': 'car',
    'cake.mp3': 'cake',
    'dog.mp3': 'dog',
    'duck.mp3': 'duck',
    'door.mp3': 'door',
    'desk.mp3': 'desk',
    'fish.mp3': 'fish',
    'fan.mp3': 'fan',
    'fox.mp3': 'fox',
    'food.mp3': 'food',
    'girl.mp3': 'girl',
    'game.mp3': 'game',
    'goat.mp3': 'goat',
    'gift.mp3': 'gift',
    'hat.mp3': 'hat',
    'hand.mp3': 'hand',
    'home.mp3': 'home',
    'horse.mp3': 'horse',
    'jam.mp3': 'jam',
    'jump.mp3': 'jump',
    'juice.mp3': 'juice',
    'jet.mp3': 'jet',
    'king.mp3': 'king',
    'kid.mp3': 'kid',
    'kite.mp3': 'kite',
    'key.mp3': 'key',
    'lion.mp3': 'lion',
    'leg.mp3': 'leg',
    'leaf.mp3': 'leaf',
    'lamp.mp3': 'lamp',
    'moon.mp3': 'moon',
    'map.mp3': 'map',
    'milk.mp3': 'milk',
    'mouse.mp3': 'mouse',
    'nest.mp3': 'nest',
    'net.mp3': 'net',
    'nose.mp3': 'nose',
    'nut.mp3': 'nut',
    'pig.mp3': 'pig',
    'pen.mp3': 'pen',
    'pan.mp3': 'pan',
    'pet.mp3': 'pet',
    'queen.mp3': 'queen',
    'quick.mp3': 'quick',
    'quiet.mp3': 'quiet',
    'quiz.mp3': 'quiz',
    'red.mp3': 'red',
    'run.mp3': 'run',
    'rain.mp3': 'rain',
    'rat.mp3': 'rat',
    'sun.mp3': 'sun',
    'sit.mp3': 'sit',
    'sea.mp3': 'sea',
    'sock.mp3': 'sock',
    'top.mp3': 'top',
    'ten.mp3': 'ten',
    'toy.mp3': 'toy',
    'tree.mp3': 'tree',
    'van.mp3': 'van',
    'vet.mp3': 'vet',
    'vest.mp3': 'vest',
    'vine.mp3': 'vine',
    'web.mp3': 'web',
    'win.mp3': 'win',
    'walk.mp3': 'walk',
    'wall.mp3': 'wall',
    'box.mp3': 'box',
    'six.mp3': 'six',
    'mix.mp3': 'mix',
    'yes.mp3': 'yes',
    'you.mp3': 'you',
    'yard.mp3': 'yard',
    'year.mp3': 'year',
    'zoo.mp3': 'zoo',
    'zip.mp3': 'zip',
    'zero.mp3': 'zero',
    'zebra.mp3': 'zebra'
}

# 确保音频目录存在
os.makedirs('../public/audio', exist_ok=True)

# 只生成不存在的音频文件
for filename, text in audio_files.items():
    file_path = f'../public/audio/{filename}'
    if not os.path.exists(file_path):
        print(f'生成音频: {filename}')
        generate_audio(text, filename)
    else:
        print(f'跳过已存在的音频: {filename}')